PATH := node_modules/.bin:$(PATH)
SHELL := /bin/bash

STYLUS_FILES := $(shell find ./public/styl -name \*.styl -print)

#All files which aren't generated by running make
HTML_SOURCE_FILES := $(shell find . -not -name "*.css" -not -name "*.html" -not -path "./node_modules/*" -not -path "./.git/*" -type f -print)



# Tasks
.PHONY: update-contributors dist

all: build

serve: all
	http-server . -p 8000

# Force rebuild
dist: update-contributors public/css/main.css
	node build.js

build: index.html public/css/main.css

index.html: $(HTML_SOURCE_FILES)
	node build.js

public/css/main.css: public/styl/main.styl $(STYLUS_FILES)
	stylus -I public/styl < $< > $@

update-contributors:
	node lib/calculate-contributions.js
	node lib/get-core-contributors.js
